### ISSUE TITLE
Register KnetNLPModels.jl

### ISSUE THREAD

**Issue by paraynaud** [JuliaSmoothOptimizers/KnetNLPModels.jl#23]

**Comment by paraynaud** [comment]
I worked!
See the [Registrator response](https://github.com/JuliaSmoothOptimizers/KnetNLPModels.jl/commit/ea576b9fdeecdd5a8f886a3ade4b9b8065ead08f#commitcomment-77200006).

**Comment by dpo** [comment]
Great news!
