### ISSUE TITLE
Issue with docstring of accuracy function

### ISSUE THREAD

**Issue by farhadrclass** [JuliaSmoothOptimizers/KnetNLPModels.jl#33]
The doc string mentioned it uses whole test datasets but the code suggests that it uses the mini_batch_test.
I think we need to either remove the docstring and write a new one or include the functionality

**Comment by dpo** [comment]
The docstring is quite confusing:
> Compute the accuracy of the network nlp.chain given the data in nlp.minibatch_test. The computation of accuracy is based on the whole test dataset nlp.data_test.

It says that it uses the test minibatch, but then it says that it uses the whole test dataset.

The code certainly suggests that it uses the test minibatch: https://github.com/JuliaSmoothOptimizers/KnetNLPModels.jl/blob/6e4c589f036e8f26144ebf141166ab7b4c22ac8d/src/utils.jl#L50

I think it should simply use the whole dataset and the docstring should be fixed.
